language: ruby
rvm:
- 2.1
install: pip install --user s3cmd
script: ./cibuild.sh
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
git:
  depth: 10
deploy:
  skip_cleanup: true
  provider: script
  script: ./s3_dev_push.sh
  on:
    branch: develop
before_install:
- openssl aes-256-cbc -K $encrypted_e2db0eb08244_key -iv $encrypted_e2db0eb08244_iv
  -in s3cfg-dev.enc -out s3cfg-dev -d
