# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Door43
email: info@door43.org
description: Door43 is an open-access translation platform for creating, translating, and distributing legally-unrestricted discipleship resources.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://door43.org" # the base hostname & protocol for your site
# Build settings

exclude: [Gemfile*, README.md]
keep_files: [assets, assets/docs, assets/vid, assets/img, assets/fonts]

gems:
  - jekyll-sitemap

markdown: kramdown
