# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Door43
email: help@door43.org
description: unrestricted biblical content in every language
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://door43.org"

# Build settings
exclude: [Gemfile*, README.md, LICENSE, s3_excludes, s3_push]
keep_files: [assets, assets/docs, assets/vid, assets/img, assets/fonts]

gems:
  - jekyll-sitemap

markdown: kramdown
